-- auto Generated on 2017-11-08 16:43:02 
-- DROP TABLE IF EXISTS `show`;
CREATE TABLE `show` (
    `id` INTEGER(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'id',
    `show_num` BIGINT NOT NULL DEFAULT -1 COMMENT 'showNum',
    `show_date` DATETIME NOT NULL DEFAULT '1000-01-01 00:00:00' COMMENT 'showDate',
    `created` DATETIME NOT NULL DEFAULT '1000-01-01 00:00:00' COMMENT 'created',
    PRIMARY KEY (`id`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT 'show';
